<?php
// Variables
return [
  "creatorName" => "Codebumble Inc.",
  "creatorUrl" => "https://codebumble.net",
  "templateName" => "Monarch",
  "templateSuffix" => "Your Streaming Platform",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "Enjoy your Movie Time with Your Family and Friends. Lets Make it more easier.",
  "support_mail" => "support@codebumble.net",
  "url" => "monarch.codebumble.net",
  "templateKeyword" => "movie, cinema, tvseries, film, fileserver",
  "licenseUrl" => "https://themeforest.net/licenses/standard",
  "livePreview" => "https://demos.pixinvent.com/vuexy-html-admin-template/landing/",
  "productPage" => "https://1.envato.market/vuexy_admin",
  "support" => "https://pixinvent.ticksy.com/",
  "moreThemes" => "https://1.envato.market/pixinvent_portfolio",
  "documentation" => "https://demos.pixinvent.com/vuexy-html-admin-template/documentation",
  "generator" => "",
  "changelog" => "https://demos.pixinvent.com/vuexy/changelog.html",
  "repository" => "https://github.com/pixinvent/vuexy-html-admin-template",
  "gitRepo" => "pixinvent",
  "gitRepoAccess" => "vuexy-html-admin-template",
  "githubFreeUrl" => "https://tools.pixinvent.com/github/github-access",
  "facebookUrl" => "https://facebook.com/codebumble",
  "twitterUrl" => "https://twitter.com/codebumble",
  "githubUrl" => "https://github.com/pixinvent",
  "dribbbleUrl" => "https://dribbble.com/pixinvent",
  "instagramUrl" => "https://instagram.com/codebumble"
];
